version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "3001:8080"
    restart: always
  codimd:
    # you can use image or custom build below
    image: localhost/hackmdio/hackmd:2.1.0
    # build:
    #   context: ..
    #   dockerfile: ./deployments/Dockerfile
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
      - CMD_PLANTUML_SERVER=http://192.168.179.14:3001
    depends_on:
      - database
      - plantuml
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
